image: cirrusci/flutter:stable

stages:
  - build
  - deploy

build_apk:
  stage: build
  script:
    - flutter build apk --release
    - flutter build appbundle --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk


deploy:
  stage: deploy
  script:
    - echo "Deploying app..."
