image: cirrusci/flutter:3.16.9

stages:
  - build

build_apk:
  stage: build
  script:
    - flutter --version
    - flutter pub get
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk