image: cirrusci/flutter:stable

stages:
  - test
  - build
  - deploy

unit_tests:
  stage: test
  script:
    - flutter test
  tags:
    - flutter

build_apk:
  stage: build
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
  tags:
    - flutter

deploy:
  stage: deploy
  script:
    - echo "Deploying app..."
  tags:
    - flutter