image: instrumentisto/flutter:latest

stages:
  - build

build_apk:
  stage: build
  script:
    - flutter --version
    - flutter update
    - flutter upgrade
    - flutter pub get
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk