android:
  stage: build
  script:
    - flutter build apk --release
    - flutter build appbundle --release
    - sudo bundle install
    - cd android && bundle exec fastlane move_files
  artifacts:
    paths:
      - build/artifacts/
  tags:
    - flutter