name: smarthajiri
description: "Digital Attendance System"
publish_to: "none"

version: 3.4.8+27

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.4
  device_info_plus: ^11.3.0
  firebase_admin: ^0.3.0+1
  firebase_auth: ^5.1.4
  firebase_core: ^3.4.0
  firebase_database: ^11.0.4
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^6.0.0
  firebase_messaging: ^15.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.2.2
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  html: ^0.15.4
  http: ^1.3.0
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  location: ^8.0.0
  local_auth: ^2.3.0
  package_rename: ^1.7.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  refresh: ^1.0.1
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/gwt_logo.jpg
    - assets/images/checkin.webp
    - assets/images/thumb_bio.png

# package_rename
# run: dart run package_rename
package_rename_config:
  android:
    app_name: GWT-HRIS
    package_name: com.xelwel.gwt # changed from com.xelwel.manipal

# flutter_launcher_icons
# run: dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/gwt_logo.jpg" # <-- put your new logo here
